name: PR Validation

on:
  pull_request:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install htmlhint stylelint
      - name: Lint HTML
        run: npx htmlhint "/*.html"
      - name: Lint CSS
        run: npx stylelint "/*.css"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install parcel
      - name: Build Project
        run: npx parcel build src/*
